# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 491)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 9, 781, 191))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lineEdit_1 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_1)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lineEdit_6 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_7 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.lineEdit_9 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_10 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_10)
        self.label_21 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_21)
        self.lineEdit_21 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_21)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 310, 781, 141))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lineEdit_11 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_11.setText(_fromUtf8(""))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_11)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_12 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_12.setText(_fromUtf8(""))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_12)
        self.lineEdit_13 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_13.setText(_fromUtf8(""))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_13)
        self.lineEdit_14 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_14.setText(_fromUtf8(""))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_14)
        self.lineEdit_15 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_15.setText(_fromUtf8(""))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_15)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.lineEdit_16 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_16.setText(_fromUtf8(""))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_16)
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_17 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_17.setText(_fromUtf8(""))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_17)
        self.lineEdit_18 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_18.setText(_fromUtf8(""))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_18)
        self.lineEdit_19 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_19.setText(_fromUtf8(""))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_19)
        self.lineEdit_20 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_20.setText(_fromUtf8(""))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_20)
        self.horizontalLayout_2.addLayout(self.formLayout_5)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(14, 272, 771, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Winch Battery Calculator", None))
        self.lineEdit_1.setText(_translate("MainWindow", "12", None))
        self.label.setText(_translate("MainWindow", "Motor Nominal Voltage (Vnom)", None))
        self.label_2.setText(_translate("MainWindow", "Motor Stall Torque at Vnom (Nm)", None))
        self.label_3.setText(_translate("MainWindow", "Motor ESR (Ohm)", None))
        self.label_4.setText(_translate("MainWindow", "Motor No Load Current at Vnom (A)", None))
        self.label_5.setText(_translate("MainWindow", "Motor No Load RPM at Vnom (RPM)", None))
        self.lineEdit_2.setText(_translate("MainWindow", "2.42", None))
        self.lineEdit_3.setText(_translate("MainWindow", "0.091", None))
        self.lineEdit_4.setText(_translate("MainWindow", "2.7", None))
        self.lineEdit_5.setText(_translate("MainWindow", "5310", None))
        self.lineEdit_6.setText(_translate("MainWindow", "0.06", None))
        self.label_6.setText(_translate("MainWindow", "Spool Diameter (m)", None))
        self.label_7.setText(_translate("MainWindow", "Input Voltage (V)", None))
        self.label_8.setText(_translate("MainWindow", "PWM Duty Cycle (%)", None))
        self.label_9.setText(_translate("MainWindow", "Battery Capacity (Ah)", None))
        self.label_10.setText(_translate("MainWindow", "Motor Torque Load (%)", None))
        self.lineEdit_7.setText(_translate("MainWindow", "12", None))
        self.lineEdit_8.setText(_translate("MainWindow", "100", None))
        self.lineEdit_9.setText(_translate("MainWindow", "80", None))
        self.lineEdit_10.setText(_translate("MainWindow", "13", None))
        self.label_21.setText(_translate("MainWindow", "Gear Ratio", None))
        self.lineEdit_21.setText(_translate("MainWindow", "256", None))
        self.label_11.setText(_translate("MainWindow", "Max Torque Available (Nm)", None))
        self.label_12.setText(_translate("MainWindow", "Load on Output Shaft (Nm)", None))
        self.label_13.setText(_translate("MainWindow", "Effective Motor Voltage (V)", None))
        self.label_14.setText(_translate("MainWindow", "Input Current (A)", None))
        self.label_15.setText(_translate("MainWindow", "Runtime (hours)", None))
        self.label_16.setText(_translate("MainWindow", "Power In (W)", None))
        self.label_17.setText(_translate("MainWindow", "Power Out (W)", None))
        self.label_18.setText(_translate("MainWindow", "Efficiency (%)", None))
        self.label_19.setText(_translate("MainWindow", "Shaft RPM (RPM)", None))
        self.label_20.setText(_translate("MainWindow", "Travel Speed (km/h)", None))
        self.pushButton.setText(_translate("MainWindow", "Calculate", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

